/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_study;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void appHasAGreeting() {
        App app = new App();
        assertTrue(app.isHelloWorld("Hello Wrold"));
        assertEquals(app.divideNumber(5), 2);
        assertNotNull(app.findArray());
        assertEquals(app.parseInt("100"), 100);
        assertEquals(app.whileMethod(10), 10);
    }
}
