/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_study;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testAppMethod() {
        Calculator calculator = new Calculator();

        assertEquals(calculator.addtion(10, 20));

        assertEquals(calculator.subtraction(30, 10));

        assertEquals(calculator.multiplication(10, 20));
        
        assertEquals(calculator.division(20, 20));
    }
}

