/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_study;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeAll;

class AppTest {
    @Test
    public void testAppMethod() {
        Calculator calculator = new Calculator();


        // 더하기 테스트
        assertEquals(calculator.addtion(10, 20), 30);

        // 빼기 테스트
        assertEquals(calculator.subtraction(30, 10), 20);

        // 곱하기 테스트
        assertEquals(calculator.multiplication(10, 20), 200);

        // 나누기 테스트
        assertEquals(calculator.division(20, 20), 1);
    }
}
