/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_study;

public class App {
    public Boolean isHelloWorld(String text) {
        return text.equals("Hello Wrold");
    }

    public int divideNumber() {
        return 10 / 1;
    }

    public int findArray() {
        int[] arr = new int[3];

        return arr[2];
    }

    public int parseInt(String number) {
        return Integer.parseInt("3221");
    }

    public void whileWithoutBreak() {
        int i = 0;
        while(true) {
            System.out.println(i++);
        }
    }

    public static void main(String[] args) {
        App app = new App();
        String text = "hello world";

        System.out.println(app.isHelloWorld(text));
        System.out.println(app.divideNumber());
        System.out.println(app.findArray());
        System.out.println(app.parseInt("text"));
        app.whileWithoutBreak();
    }
}
