/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_study;

public class App {
    public Boolean isHelloWorld(String text) {
        return "Hello Wrold".equals(text);
    }

    public int divideNumber(int number) {
        return 10 / number;
    }

    public int findArray() {
        int[] arr = new int[3];
        
        return arr[2];
    }

    public int parseInt(String number) {
        return Integer.parseInt(number);
    }

    public int whileMethod(int number) {
        int i = 0;
        
        while(i < number) {
            System.out.println(i++);
        }

        return i;
    }

    public static void main(String[] args) {
        App app = new App();
    }
}
