/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package git_study;

public class App {
    public Boolean isHelloWorld(String text) {
        return text.equals("Hello World");
    }

    public int divideNumber() {
        return 10 / 2;
    }

    public int findArray() {
        int[] arr = new int[5];
        return arr[4];
    }

    public int parseInt(String number) {
         try {
        return Integer.parseInt(number);
    } catch (NumberFormatException e) {
        System.err.println("Invalid number format");
        return 0;  // Or handle the error in an appropriate way
    }
    }

    public void whileWithoutBreak() {
        int i = 0;
    while (i < 10) {  // Add a condition to break the loop
        System.out.println(i++);
    }
    }

    public static void main(String[] args) {
        App app = new App();
        String text = null;

        System.out.println(app.isHelloWorld(text));
        System.out.println(app.divideNumber());
        System.out.println(app.findArray());
        System.out.println(app.parseInt("text"));
        app.whileWithoutBreak();
    }
}
